import { ShelterEntity } from "@/domain/entities/shelter.entity";
import type { IShelterRepository } from "@/domain/repositories/shelter.repository";
import type { IHandler } from "@/infrastructure/shared/mediator";

export class CreateShelterCommand {
	constructor(
		public readonly name: string,
		public readonly email: string,
		public readonly address?: string,
		public readonly latitude?: number,
		public readonly longitude?: number,
		public readonly capacity?: number,
	) {}
}

import type { ShelterCreatedEvent } from "@/domain/events/domain-events";
import type { RabbitMQService } from "@/infrastructure/services/rabbitmq.service";

export class CreateShelterHandler
	implements IHandler<CreateShelterCommand, ShelterEntity>
{
	constructor(
		private shelterRepository: IShelterRepository,
		private rabbitMQService: RabbitMQService,
	) {}

	async handle(command: CreateShelterCommand): Promise<ShelterEntity> {
		const shelter = new ShelterEntity(
			"", // ID generated by DB
			command.name,
			command.email,
			command.address,
			command.latitude,
			command.longitude,
			command.capacity,
		);
		const createdShelter = await this.shelterRepository.create(shelter);

		const event: ShelterCreatedEvent = {
			id: createdShelter.id,
			name: createdShelter.name,
			email: createdShelter.email,
			address: createdShelter.address || undefined,
			latitude: createdShelter.latitude || undefined,
			longitude: createdShelter.longitude || undefined,
			capacity: createdShelter.capacity || undefined,
		};

		await this.rabbitMQService.publish("shelter_events", {
			event: "ShelterCreated",
			data: event,
		});

		return createdShelter;
	}
}
