import { PetEntity } from "@/domain/entities/pet.entity";
import type { IPetRepository } from "@/domain/repositories/pet.repository";
import type { IHandler } from "@/infrastructure/shared/mediator";

export class CreatePetCommand {
	constructor(
		public readonly name: string,
		public readonly status: string,
		public readonly kindId: string,
		public readonly genderId: string,
		public readonly raceId?: string | null,
		public readonly shelterId?: string | null,
		public readonly ownerEmail?: string | null,
		public readonly ownerId?: string | null,
	) {}
}

import type { PetCreatedEvent } from "@/domain/events/domain-events";
import type { RabbitMQService } from "@/infrastructure/services/rabbitmq.service";
import { emitNewPetReported } from "@/infrastructure/services/socket.service";

export class CreatePetHandler implements IHandler<CreatePetCommand, PetEntity> {
	constructor(
		private petRepository: IPetRepository,
		private rabbitMQService: RabbitMQService,
	) {}

	async handle(command: CreatePetCommand): Promise<PetEntity> {
		const pet = new PetEntity(
			"", // ID generated by DB
			command.name,
			command.status,
			command.kindId,
			command.genderId,
			command.shelterId,
			command.ownerEmail,
			command.ownerId,
			command.raceId,
		);
		const createdPet = await this.petRepository.create(pet);

		const event: PetCreatedEvent = {
			id: createdPet.id,
			name: createdPet.name,
			status: createdPet.status,
			kindId: createdPet.kindId,
			genderId: createdPet.genderId,
			shelterId: createdPet.shelterId,
			ownerEmail: createdPet.ownerEmail || undefined,
		};

		await this.rabbitMQService.publish("pet_events", {
			event: "PetCreated",
			data: event,
		});

		// Emitir evento de socket para notificaciones en tiempo real
		emitNewPetReported({
			id: createdPet.id,
			name: createdPet.name,
			status: createdPet.status,
		});

		return createdPet;
	}
}
