import { IHandler } from '@/infrastructure/shared/mediator';
import { IShelterRepository } from '@/domain/repositories/shelter.repository';
import { ShelterEntity } from '@/domain/entities/shelter.entity';

export class CreateShelterCommand {
    constructor(
        public readonly name: string,
        public readonly email: string,
        public readonly address?: string,
        public readonly latitude?: number,
        public readonly longitude?: number,
        public readonly capacity?: number
    ) { }
}

export class CreateShelterHandler implements IHandler<CreateShelterCommand, ShelterEntity> {
    constructor(private shelterRepository: IShelterRepository) { }

    async handle(command: CreateShelterCommand): Promise<ShelterEntity> {
        const shelter = new ShelterEntity(
            '', // ID generated by DB
            command.name,
            command.email,
            command.address,
            command.latitude,
            command.longitude,
            command.capacity
        );
        return await this.shelterRepository.create(shelter);
    }
}
