import { IHandler } from '@/infrastructure/shared/mediator';
import { IMediaRepository } from '@/domain/repositories/media.repository';
import { MediaEntity } from '@/domain/entities/media.entity';

export class CreateMediaCommand {
    constructor(
        public readonly url: string,
        public readonly storageKey: string,
        public readonly provider: string,
        public readonly type: string,
        public readonly latitude: number,
        public readonly longitude: number,
        public readonly petId: string
    ) { }
}

export class CreateMediaHandler implements IHandler<CreateMediaCommand, MediaEntity> {
    constructor(private mediaRepository: IMediaRepository) { }

    async handle(command: CreateMediaCommand): Promise<MediaEntity> {
        const media = new MediaEntity(
            '', // ID generated by DB
            command.url,
            command.storageKey,
            command.provider,
            command.type,
            command.latitude,
            command.longitude,
            command.petId
        );
        return await this.mediaRepository.create(media);
    }
}
