import { IHandler } from '@/infrastructure/shared/mediator';
import { IMediaRepository } from '@/domain/repositories/media.repository';
import { MediaEntity } from '@/domain/entities/media.entity';

export class CreateMediaCommand {
    constructor(
        public readonly url: string,
        public readonly storageKey: string,
        public readonly provider: string,
        public readonly type: string,
        public readonly latitude: number,
        public readonly longitude: number,
        public readonly geohash: string | null,
        public readonly petId: string
    ) { }
}

import { RabbitMQService } from '@/infrastructure/services/rabbitmq.service';
import { MediaCreatedEvent } from '@/domain/events/domain-events';

export class CreateMediaHandler implements IHandler<CreateMediaCommand, MediaEntity> {
    constructor(
        private mediaRepository: IMediaRepository,
        private rabbitMQService: RabbitMQService
    ) { }

    async handle(command: CreateMediaCommand): Promise<MediaEntity> {
        const media = new MediaEntity(
            '', // ID generated by DB
            command.url,
            command.storageKey,
            command.provider,
            command.type,
            command.latitude,
            command.longitude,
            command.geohash,
            command.petId
        );
        const createdMedia = await this.mediaRepository.create(media);

        const event: MediaCreatedEvent = {
            petId: createdMedia.petId,
            url: createdMedia.url,
            type: createdMedia.type
        };

        // Publish to pet_events stream so Pet Read Model can be updated with new photo
        await this.rabbitMQService.publish('pet_events', {
            event: 'MediaUploaded',
            data: event
        });

        return createdMedia;
    }
}
