import { IHandler } from '@/infrastructure/shared/mediator';
import { IShelterRepository } from '@/domain/repositories/shelter.repository';
import { ShelterEntity } from '@/domain/entities/shelter.entity';

export class CreateShelterCommand {
    constructor(
        public readonly name: string,
        public readonly email: string,
        public readonly address?: string,
        public readonly latitude?: number,
        public readonly longitude?: number,
        public readonly capacity?: number
    ) { }
}

import { RabbitMQService } from '@/infrastructure/services/rabbitmq.service';
import { ShelterCreatedEvent } from '@/domain/events/domain-events';

export class CreateShelterHandler implements IHandler<CreateShelterCommand, ShelterEntity> {
    constructor(
        private shelterRepository: IShelterRepository,
        private rabbitMQService: RabbitMQService
    ) { }

    async handle(command: CreateShelterCommand): Promise<ShelterEntity> {
        const shelter = new ShelterEntity(
            '', // ID generated by DB
            command.name,
            command.email,
            command.address,
            command.latitude,
            command.longitude,
            command.capacity
        );
        const created.shelter = await this.shelterRepository.create(shelter);

        const event: ShelterCreatedEvent = {
            id: created.shelter.id,
            name: created.shelter.name,
            email: created.shelter.email,
            address: created.shelter.address || undefined,
            latitude: created.shelter.latitude || undefined,
            longitude: created.shelter.longitude || undefined,
            capacity: created.shelter.capacity || undefined
        };

        await this.rabbitMQService.publish('shelter_events', {
            event: 'ShelterCreated',
            data: event
        });

        return created.shelter;
    }
}
