import { IHandler } from '@/infrastructure/shared/mediator';
import { IPetRepository } from '@/domain/repositories/pet.repository';
import { PetEntity } from '@/domain/entities/pet.entity';

export class CreatePetCommand {
    constructor(
        public readonly name: string,
        public readonly status: string,
        public readonly kindId: string,
        public readonly genderId: string,
        public readonly shelterId?: string | null,
        public readonly ownerEmail?: string
    ) { }
}

export class CreatePetHandler implements IHandler<CreatePetCommand, PetEntity> {
    constructor(private petRepository: IPetRepository) { }

    async handle(command: CreatePetCommand): Promise<PetEntity> {
        const pet = new PetEntity(
            '', // ID generated by DB
            command.name,
            command.status,
            command.kindId,
            command.genderId,
            command.shelterId,
            command.ownerEmail
        );
        return await this.petRepository.create(pet);
    }
}
